### PR TITLE
add theme-Mego

### PR DESCRIPTION
**Pull request by wflac**
辛苦帮忙审批下，并发布到应用商店。

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
Hi @wflac ，我从 https://github.com/wflac/theme-Mego/releases/tag/1.0.0 下载主题包后，无法正常安装该主题。

**Comment by wflac** [comment]
@JohnNiang 已 ok

**Review by JohnNiang — COMMENTED** [review]
Please fix https://github.com/wflac/theme-Mego/issues/2 before merging.

**Review by JohnNiang — COMMENTED** [review]
/approve

Thanks for your contribution!

**Review by ruibaby — COMMENTED** [review]
/lgtm

https://www.halo.run/store/apps/app-meJsF

**Review by ruibaby — APPROVED** [review]

**Pull request merged**
